# Generated by Django 5.0.3 on 2024-03-10 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorsucursal',
            name='lista_chatarra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_sucursal_chatarra', to='lista_precios.lista'),
        ),
        migrations.AddField(
            model_name='proveedorsucursal',
            name='lista_metales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_sucursal_metales', to='lista_precios.lista'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='proveedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_mayorista', to='lista_precios.proveedorsucursal'),
        ),
    ]
