# Generated by Django 5.0.3 on 2024-03-10 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0002_proveedorsucursal_lista_chatarra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulolista',
            name='precio',
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('articulo_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='lista_precios.articulolista')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.DeleteModel(
            name='PrecioArticulo',
        ),
    ]
