# Generated by Django 5.0.3 on 2024-03-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0003_remove_articulolista_precio_historialprecio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialprecio',
            options={},
        ),
    ]
