# Generated by Django 5.0.3 on 2024-03-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0004_alter_historialprecio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='lista_precios.categoriaproveedor'),
        ),
    ]
